global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # California Housing Prediction API
  - job_name: 'housing-prediction-api'
    static_configs:
      - targets: ['mlops-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MLflow Tracking Server
  - job_name: 'mlflow-server'
    static_configs:
      - targets: ['mlflow-server:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Prometheus Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
