global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # California Housing Prediction API (local)
  - job_name: 'housing-prediction-api-local'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Local API instance
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # California Housing Prediction API (docker)
  - job_name: 'housing-prediction-api-docker'
    static_configs:
      - targets: ['172.17.0.1:8000']  # Docker bridge network
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
